"""
Django settings for livechatapp project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-k@p8(u5ym4nfrzvpurs8+%u93j8zq#t&rua6p#4!!a$7yb06*9'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = []
CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
# CSRF_TRUSTED_ORIGINS = [
#     "https://voxachat-88fl.onrender.com",
#     "https://your-react-frontend.onrender.com",
# ]



SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = os.getenv("DEBUG", "False") == "True"
# ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")
# Application definition

INSTALLED_APPS = [
    "channels",
    "corsheaders",
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'User',
    'Voxa',
]

# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [("127.0.0.1", 6379)],
#         },
#     },
# }
# import os
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts": [os.environ.get("REDIS_URL")],
#         },
#     },
# }

import os

REDIS_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379")
# REDIS_URL = os.environ.get("REDIS_URL")
print("Using REDIS_URL:", os.environ.get("REDIS_URL"))

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # must be at the top, before CommonMiddleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'livechatapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'livechatapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



AUTH_USER_MODEL = 'User.UserProfile'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',  # default: require auth
    ),
}

# CORS settings

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",       # For your local React/Vue/Svelte development
    "http://127.0.0.1:3000",
    "https://voxachat.netlify.app/", # Your actual production domain
]
CORS_ALLOWED_ORIGINS = [
    "https://voxachat.netlify.app",
    "http://localhost:3000",  # for local dev
]
CORS_ALLOW_CREDENTIALS = True

from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),   # default is 5 minutes
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),      # default is 1 day
    "ROTATE_REFRESH_TOKENS": True,                    # optional: issue new refresh on use
    "BLACKLIST_AFTER_ROTATION": True,                 # optional: blacklist old refresh
}


# ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
# ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")

# # For quick testing, you can hardcode:
# ALLOWED_HOSTS = [
#     "voxachat-88fl.onrender.com",
#     "localhost",
#     "127.0.0.1",
# ]
ALLOWED_HOSTS = ["*"]

ASGI_APPLICATION = "livechatapp.asgi.application"


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Other important checks
# Cookies enabled: Ensure your browser accepts cookies, since CSRF tokens are tied to them.

# Frontend requests: If you’re using fetch or Axios in React, include credentials and CSRF headers:

# js
# fetch("https://voxachat-88fl.onrender.com/api/endpoint/", {
#   method: "POST",
#   credentials: "include",
#   headers: {
#     "X-CSRFToken": getCookie("csrftoken"),
#     "Content-Type": "application/json",
#   },
#   body: JSON.stringify(data),
# })
# Template forms: If you’re using Django templates, make sure every <form method="POST"> includes {% csrf_token %}.

# Deployment: On Render, environment variables should be set in the dashboard, not in .env files committed to Git.